version: "3.10"

services:
  frontend:
    build:
      context: .
      dockerfile: Streamlit_Frontend/Dockerfile
    image: frontend:latest
    ports:
      - 8501:8501
    networks:
      - project_network
    depends_on:
      - backend
    volumes:
      - ./Streamlit_Frontend:/app/backend
    environment:   
      - OPENAI_API_KEY=


  backend:
    build:
      context: .
      dockerfile: FastAPI_Backend/Dockerfile
    image: backend:latest
    ports:
      - 9090:8080
    networks:
      - project_network
    environment:   
      - OPENAI_API_KEY=  

networks:
  project_network:
